name: Sync Service Directory
on:
  push:
    paths:
      - 'packages/rss/service/**'
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Service Directory
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Clone the deployment repo
          git clone https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/yourusername/rss-service-deploy.git
          
          # Copy service directory contents
          rm -rf rss-service-deploy/*
          cp -r packages/rss/service/* rss-service-deploy/
          
          # Commit and push changes
          cd rss-service-deploy
          git add .
          git commit -m "Sync from main repo" || echo "No changes to commit"
          git push