name: Sync RSS Service
on:
  push:
    paths:
      - 'packages/rss/service/**'
    branches:
      - main

jobs:
  sync-rss:
    uses: ./.github/workflows/sync-service-template.yml
    with:
      source_path: packages/rss/service
      target_repo: potlock/rss-service-template
      target_branch: main
    secrets:
      deploy_token: ${{ secrets.RSS_DEPLOY_TOKEN }}
